### ISSUE TITLE
Unable to save excel sheet in my local machine

### ISSUE THREAD

**Issue by moharora8** [justkawal/excel#109]
I am using flutter web and I have used an InkWell widget to trigger a function that creates an excel sheet and saves it in my downloads directory. Excel sheet is created successfully (I have tested it by printing its data in console) but it is not saved in my download folder.
I have used this code to save excel sheets

 **excel.encode().then((onValue) {
                            File(pt.join(outputFile))
                              ..createSync(recursive: true)
                              ..writeAsBytesSync(onValue);
                          });**
It throws the exception mentioned below. 

Error: Unsupported operation: Platform._operatingSystem
    at Object.throw_ [as throw] (http://localhost:56019/dart_sdk.js:5331:11)
    at Function._operatingSystem (http://localhost:56019/dart_sdk.js:56141:17)
    at Function.get operatingSystem [as operatingSystem] (http://localhost:56019/dart_sdk.js:56187:27)
    at get _operatingSystem (http://localhost:56019/dart_sdk.js:56100:27)
    at Function.desc.get [as _operatingSystem] (http://localhost:56019/dart_sdk.js:5836:17)
    at get isWindows (http://localhost:56019/dart_sdk.js:56118:26)
    at Function.desc.get [as isWindows] (http://localhost:56019/dart_sdk.js:5836:17)
    at Function.parentOf (http://localhost:56019/dart_sdk.js:51722:33)
    at io._File.new.get parent [as parent] (http://localhost:56019/dart_sdk.js:51742:51)
    at io._File.new.createSync (http://localhost:56019/dart_sdk.js:53040:14)
    at http://localhost:56019/packages/tiffincruise/widgets/decideorder.dart.lib.js:45175:24

**Comment by justkawal** [comment]
This would help: https://github.com/justkawal/excel#on-flutter-web

**Comment by agorneo** [comment]
Hello,
I am trying your package
It looks very promising
The "save" method does not exists in "excel" object
How can I save the excel file in the WEB?
Thank you for all this wonderful work that you have done

**Comment by justkawal** [comment]
Are you using version:

```excel: ^2.0.0-null-safety-3 ```
