### ISSUE TITLE
type 'Null' is not a subtype of type 'List<int>' in type cast.

### ISSUE THREAD

**Issue by YowFung** [justkawal/excel#143]
It throws `type 'Null' is not a subtype of type 'List<int>' in type cast` for me when I call `save()` function of `Excel` instance.

```txt
flutter: type 'Null' is not a subtype of type 'List<int>' in type cast
flutter: #0      ZipEncoder.getFileCrc32 (package:archive/src/zip_encoder.dart:91:34)
#1      ZipEncoder.addFile (package:archive/src/zip_encoder.dart:136:15)
#2      ZipEncoder.encode (package:archive/src/zip_encoder.dart:65:7)
#3      Save._save (package:excel/src/save/save_file.dart:36:25)
#4      Excel.save (package:excel/src/excel.dart:334:21)
#5      ExcelIO.save (package:common/src/execution/excel_io.dart:514:33)
#6      RunningPageLogic.exportReport (package:api_tester/views/running_page/logic.dart:402:15)
<asynchronous suspension>
```

<img width="1920" alt="iShot2022-03-11 12 03 50" src="https://user-images.githubusercontent.com/26346560/157799961-84624673-412c-42f4-a18d-e471b96c9ced.png">

**Comment by demirdev** [comment]
@YowFung use this in pubspec.yaml

```
  excel:
    git:
      url: https://github.com/justkawal/excel.git
      ref: null-safety
```

**Comment by justkawal** [comment]
@YowFung 
Soon a null-safe version will be launched on pub.dev
Until then please refer to answer from @demirdev
