### ISSUE TITLE
bug  2.0.1 can't read excel

### ISSUE THREAD

**Issue by cuishijie1991** [justkawal/excel#202]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: XmlParserException: Expected a single root element at 1:1
#0      XmlAnnotator.close (package:xml/src/xml_events/annotations/annotator.dart:108:7)
#1      XmlEventIterator.moveNext (package:xml/src/xml_events/iterator.dart:47:20)
#2      Iterable.forEach (dart:core/iterable.dart:325:23)
#3      XmlNodeDecoder.convertIterable (package:xml/src/xml_events/converters/node_decoder.dart:53:12)
#4      new XmlDocument.parse (package:xml/src/xml/nodes/document.dart:34:41)
#5      Parser._parseSharedStrings (package:excel/src/parser/parse.dart:136:32)
#6      Parser._sta
[表格1(1).xlsx](https://github.com/justkawal/excel/files/10416755/1.1.xlsx)
rtParsing (package:excel/src/parser/parse.dart:17:5)
#7      new Excel._ (package:excel/src/excel.dart:74:12)

**Comment by XSANElimos** [comment]
I had got this same problem too.
so did u solve it ?
好像[spreadsheet_decoder]库没有啥问题，公式也能读出来 这个excel公式也读不出来

**Comment by cuishijie1991** [comment]
Replaced it with library "spreadsheet_decoder"

**Comment by cuishijie1991** [comment]
> I had got this same problem too.
> so did u solve it ?
> 好像[spreadsheet_decoder]库没有啥问题，公式也能读出来 这个excel公式也读不出来

Replaced it with library "spreadsheet_decoder"
