### ISSUE TITLE
Error on Excel.decodeBytes(excelData)

### ISSUE THREAD

**Issue by christophe-andre** [justkawal/excel#248]
Error: Expected a value of type 'Iterable<XmlNode>', but got one of type 'ReversedListIterable<XmlNode>'

My code :
FilePickerResult? pickedFile = await FilePicker.platform.pickFiles(
    type: FileType.custom,
    allowedExtensions: ['xlsx'],
    allowMultiple: false,
  );

  if (pickedFile != null) {
    Uint8List? bytes = pickedFile.files.single.bytes;
    List<int> excelData = bytes!.toList();
    var excel = Excel.decodeBytes(excelData);

My dependencies :
archive: 3.3.7
xml: 6.3.0
excel: 2.1.0
collection: 1.17.1
equatable: 2.0.5

**Comment by christophe-andre** [comment]
dart_sdk.js:5463 Uncaught (in promise) Error: Expected a value of type 'Iterable<XmlNode>', but got one of type 'ReversedListIterable<XmlNode>'
    at Object.throw_ [as throw] (dart_sdk.js:5463:11)
    at Object.castError (dart_sdk.js:5422:15)
    at Object.cast [as as] (dart_sdk.js:5745:19)
    at Iterable.as_C [as as] (dart_sdk.js:5343:19)
    at [dartx.addAll] (dart_sdk.js:17757:27)
    at descendants.XmlDescendantsIterator.new.push (descendants.dart:37:11)
    at new descendants.XmlDescendantsIterator.new (descendants.dart:30:5)
    at get iterator [as iterator] (descendants.dart:24:37)
    at get iterator [as iterator] (dart_sdk.js:25932:67)
    at get iterator [as iterator] (dart_sdk.js:24970:65)
    at [Symbol.iterator] (dart_sdk.js:22896:40)
    at WhereIterable.new.forEach (dart_sdk.js:22928:29)
    at [_parseRelations] (parse.dart:47:32)
    at [_startParsing] (parse.dart:15:5)
    at new excel$.Excel.__ (excel.dart:75:12)
    at Object._newExcel (excel.dart:17:20)
    at Excel.decodeBytes (excel.dart:85:12)
    at importExcelFile (import_excel_file.dart:41:23)
    at importExcelFile.next (<anonymous>)
    at dart_sdk.js:41432:33
    at _RootZone.runUnary (dart_sdk.js:41265:59)
    at _FutureListener.thenAwait.handleValue (dart_sdk.js:36468:29)
    at handleValueCallback (dart_sdk.js:37039:49)
    at _Future._propagateToListeners (dart_sdk.js:37077:17)
    at [_completeWithValue] (dart_sdk.js:36912:23)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:36946:35)
    at Object._microtaskLoop (dart_sdk.js:41740:13)
    at _startMicrotaskLoop (dart_sdk.js:41746:13)
    at dart_sdk.js:37302:9

**Comment by FauconSpartiate** [comment]
Could you provide an example file where the error shows up?
This will help us to investigate the issue

**Comment by christophe-andre** [comment]
@FauconSpartiate . Do you mean an Excel example file or the code ?

**Comment by FauconSpartiate** [comment]
Both, but you already provided the code, so we're only missing the excel file that causes the problem.

**Comment by christophe-andre** [comment]
[Produits.csv](https://github.com/justkawal/excel/files/12209706/Produits.csv)

**Comment by christophe-andre** [comment]
Hi @FauconSpartiate . Any news about this bug ?

**Comment by FauconSpartiate** [comment]
Nope, any help for digging into the codebase is welcome.
If you're motivated, you can also do it.

**Comment by christophe-andre** [comment]
Sorry but I'm not competent enough for this

**Comment by FauconSpartiate** [comment]
@christophe-andre Still reproducible in `3.0.0`

**Comment by FauconSpartiate** [comment]
> [Produits.csv](https://github.com/justkawal/excel/files/12209706/Produits.csv)

I just tried to reproduce it, but I couldn't help but notice that you provided a .csv file and not .xlsx?
Do you also get the error by creating a new excel file and importing this csv?

**Comment by christophe-andre** [comment]
By importing the csv

**Comment by FauconSpartiate** [comment]
@christophe-andre Are you still experiencing the issue on `3.0.0`?

**Comment by christophe-andre** [comment]
Hi @FauconSpartiate 
I have another problem with on 3.0.0

My code
  FilePickerResult? pickedFile = await FilePicker.platform.pickFiles(
    type: FileType.custom,
    allowedExtensions: ['xlsx'],
    allowMultiple: false,
  );

  if (pickedFile != null) {
    var excelData = pickedFile.files.single.bytes;
    // var excel = Excel.decodeBytes(excelData);
    List<int> data = excelData as List<int>;
    var excel = Excel.decodeBytes(data);

If i don't convert into List<int> this error appears
The argument type 'Uint8List?' can't be assigned to the parameter type 'List<int>'.

The runtime error is
Uncaught (in promise) Error: Unsupported operation: Excel format unsupported. Only .xlsx files are supported
    at Object.throw_ [as throw] (dart_sdk.js:5402:11)
    at Excel.decodeBytes (excel.dart:95:7)

In attachment the file i want to import
[Ingredients.xlsx](https://github.com/justkawal/excel/files/13202170/Ingredients.xlsx)
