### ISSUE TITLE
Cannot delete sheets

### ISSUE THREAD

**Issue by horvathAdam285** [justkawal/excel#346]
Calling excel.delete(sheetName) can throw this error:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Cannot remove from an unmodifiable list
E/flutter (20043): #0      UnmodifiableListMixin.removeWhere (dart:_internal/list.dart:139:5)

The problem seems to be trying to delete from _archive.files, which is an UnmodifiableListView

**Comment by bahadirarslan** [comment]
I am facing this issue while using the `rename` function.
It tries to delete the old named sheet

**Comment by Another-Chris** [comment]
Apparently they are trying to call `removeWhere()` on `_archive.files`, which is an `UnformidableView`  
I am not sure why they make `_archive.files` unformidable but also call removeWhere on it. Dart documentation clearly says it is not supported. [removeWhere method](https://api.flutter.dev/flutter/dart-collection/UnmodifiableListView/removeWhere.html)

**Comment by Priyantha-Kingslake** [comment]
Renaming sheet throws error too. 
Renaming or deleting sheets is not possible.

```
    final excel = Excel.createExcel();
    excel.rename("Sheet1", "newName");
```

this throws following error for me

>Error
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
dart-sdk/lib/internal/list.dart 139:5                                        removeWhere
packages/excel/src/excel.dart 265:16                                         delete
packages/excel/src/excel.dart 199:7                                          rename

**Comment by luizgpa** [comment]
Could anyone please confirm if that issue continues on 4.0.x?

**Comment by mikeloomisgg** [comment]
I'm able to rename sheets that I create. 
This is on windows 11, lib version v4.0.2

```
  Excel excel = Excel.createExcel();
  var overviewSheet = excel['OVERVIEW'];
  excel.rename("OVERVIEW", "REQUIREMENTS");
```

I cannot delete "Sheet1", however. It gives me this error:
```
Unhandled exception:
Unsupported operation: Cannot remove from an unmodifiable list
#0      UnmodifiableListMixin.removeWhere (dart:_internal/list.dart:139:5)
#1      Excel.delete (package:excel/src/excel.dart:279:22)
#2      main (*)
```

**Comment by mikeloomisgg** [comment]
If I remove the block of code that is throwing an exception then I can delete Sheet1:
```
      // _archive.files.removeWhere((file) {
      //   return file.name.toLowerCase() == _xmlSheetId[sheet]?.toLowerCase();
      // });
```

What is the purpose of deleting from the unmodifiable list?

**Comment by mikeloomisgg** [comment]
I upgraded to v4.0.3 and this was fixed, even for Sheet1.
