### ISSUE TITLE
FormatException

### ISSUE THREAD

**Issue by razzlakki** [justkawal/excel#93]
Facing below issue with valid xlsx file. Uploaded same file in the example

example.xlsx
Error: FormatException: Unexpected extension byte (at offset 41)
    at Object.throw_ [as throw] (http://localhost:51909/dart_sdk.js:5333:11)
    at convert._Utf8Decoder.new.convertGeneral (http://localhost:51909/dart_sdk.js:49223:19)
    at convert._Utf8Decoder.new.convertSingle (http://localhost:51909/dart_sdk.js:49195:19)
    at Utf8Decoder.convert (http://localhost:51909/dart_sdk.js:49054:67)
    at Utf8Codec.decode (http://localhost:51909/dart_sdk.js:48760:22)
    at _incrementCounter (http://localhost:51909/packages/nihepimporter/main.dart.lib.js:463:35)
    at _incrementCounter.next (<anonymous>)
    at http://localhost:51909/dart_sdk.js:39031:33
    at _RootZone.runUnary (http://localhost:51909/dart_sdk.js:38888:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:51909/dart_sdk.js:33874:29)
    at handleValueCallback (http://localhost:51909/dart_sdk.js:34434:49)
    at Function._propagateToListeners (http://localhost:51909/dart_sdk.js:34472:17)
    at _Future.new.[_completeWithValue] (http://localhost:51909/dart_sdk.js:34314:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:51909/dart_sdk.js:34337:35)
    at Object._microtaskLoop (http://localhost:51909/dart_sdk.js:39175:13)
    at _startMicrotaskLoop (http://localhost:51909/dart_sdk.js:39181:13)
    at http://localhost:51909/dart_sdk.js:34688:9

**Comment by justkawal** [comment]
@razzlakki 

Can you please provider a reproducible code or excel file in which you are having this issue ???

**Comment by FauconSpartiate** [comment]
@razzlakki 
As its long to get any response, I think the error is fixed.

If the issue still persists then please feel free to re-open the issue again.
